### snoping create users
POST http://localhost:4040/createuser HTTP/1.1
Content-type: application/json

{
    "email": "petruha@example.com",
    "password": "123456"
}

### snoping authorization users
POST http://localhost:4040/session HTTP/1.1
Content-type: application/json

{
    "email": "example@example.com",
    "password": "123456"
}

### snoping private page "whoami"
GET http://localhost:4040/private/whoami HTTP/1.1

### snoping private page "todo-list"
POST http://localhost:4040/private/createtodo HTTP/1.1
Content-type: application/json

{
    "text": "Hello world!",
    "date": "2022-03-16"
}
### snoping private page get todo list
GET http://localhost:4040/private/listtodo HTTP/1.1
